/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Chủ tài khoản tự đổi mật khẩu; mọi phiên **khác** bị thu hồi.
         *
         *     Hai transaction: kiểm mật khẩu hiện tại (có bộ đếm khóa + nhật ký, commit cả
         *     khi sai — xem `auth_service.verify_current_password`), rồi mới ghi.
         *
         *     Thu hồi phiên khác là phần không được quên: người ta đổi mật khẩu chính vì
         *     nghi nó đã lộ, và một phiên mở sẵn trên máy khác vẫn sống nếu không đuổi.
         */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Cấp phiên đăng nhập (FR-NFR-010, FR-NFR-016).
         *
         *     Không mở transaction ở đây: `authenticate` phải tự quản transaction của nó
         *     vì đường **thất bại** cũng cần commit (bộ đếm khóa + nhật ký). Xem
         *     `kernel/security/auth_service.py`.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Thu hồi phiên đang dùng. Gọi lại với token đã thu hồi trả 401.
         *
         *     Làm được ở **mọi** trạng thái phiên: một người đang kẹt ở màn hình đăng ký
         *     2FA hay màn hình đổi mật khẩu tạm vẫn phải đăng xuất được.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Danh tính của phiên hiện tại — client gọi lúc khởi động để khôi phục phiên.
         *
         *     `session_scope` và `must_change_password` cho client biết phải đưa người
         *     dùng tới màn hình nào trước khi cho vào phần nghiệp vụ.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Totp
         * @description Xác nhận thiết bị sinh mã hoạt động — từ đây 2FA mới chặn được đăng nhập.
         *
         *     Thu hồi luôn phiên đang dùng khi nó là phiên hạn chế: phiên đó được cấp cho
         *     một tài khoản **chưa** qua lớp thứ hai, nên nó không được tự nâng cấp thành
         *     phiên đầy đủ. Người dùng đăng nhập lại và lần này nhập mã — đó cũng là lần
         *     thử thật đầu tiên của thiết bị vừa đăng ký.
         */
        post: operations["confirm_totp_api_v1_auth_totp_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enroll Totp
         * @description Sinh bí mật 2FA mới và trả URI dựng mã QR. Chưa có hiệu lực tới khi xác nhận.
         *
         *     Gọi được bằng **phiên hạn chế** — đó là toàn bộ lý do phiên hạn chế tồn tại:
         *     tài khoản bị bắt bật 2FA mà chưa có thiết bị thì đây là endpoint duy nhất nó
         *     còn dùng được.
         */
        post: operations["enroll_totp_api_v1_auth_totp_enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Hàng đợi của dữ liệu kế toán đang mở, mới nhất trước.
         *
         *     RLS lọc theo chi nhánh trước khi mã này chạy, nên "mọi job" ở đây nghĩa là
         *     mọi job **người gọi được thấy**.
         *
         *     Bộ lọc trạng thái khai bằng `JobStatus` để FastAPI trả `422` cho giá trị lạ.
         *     Nhận `str` trần thì `?status=runing` cho ra danh sách rỗng — client đọc
         *     thành "hàng đợi trống" và không có gì báo là đã gõ sai.
         */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /**
         * Enqueue Job
         * @description Xếp một tác vụ vào hàng đợi của dữ liệu kế toán đang mở.
         *
         *     `202` chứ không `201`: yêu cầu đã được ghi nhận, kết quả chưa có. Client
         *     theo dõi bằng `GET /api/v1/jobs/{id}`.
         *
         *     Quyền riêng của loại tác vụ kiểm **trong thân hàm** vì nó phụ thuộc thân
         *     request; dependency ở chữ ký giữ mức sàn, nên người không có quyền dùng hàng
         *     đợi dừng lại từ trước.
         *
         *     Chi nhánh của job = chi nhánh **đang thao tác** của người yêu cầu. Đó là thứ
         *     quyết định phạm vi RLS mà thân job chạy dưới, nên nó phải là chi nhánh của
         *     người bấm nút chứ không phải một tham số client gửi lên.
         */
        post: operations["enqueue_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Job Types
         * @description Loại tác vụ mà **bản cài này** biết chạy.
         *
         *     Lọc theo quyền của người gọi: danh sách trả về là những việc họ bấm được,
         *     nên màn hình không hiện một nút chắc chắn trả `403`.
         */
        get: operations["list_job_types_api_v1_jobs_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Trạng thái + tiến độ của một tác vụ.
         */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Yêu cầu dừng một tác vụ.
         *
         *     Đặt cờ chứ không giết tiến trình: worker dừng ở **ranh giới lô** gần nhất.
         *     Giết giữa một bút toán phân bổ là cách tạo ra sổ lệch, nên phản hồi ở đây là
         *     "đã ghi nhận", không phải "đã dừng" — trạng thái thật đọc ở lần `GET` sau.
         */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Access
         * @description Quyền của tôi trong dữ liệu kế toán đang mở.
         */
        get: operations["my_access_api_v1_system_access_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Audit Log
         * @description Nhật ký nghiệp vụ của dataset đang mở (FR-NFR-013).
         *
         *     Không có bộ lọc chi nhánh trong câu truy vấn, và đó là điểm chính: RLS trên
         *     bảng gốc cắt theo GUC `ket.branch_ids` mà transaction đã đặt, nên cả `total`
         *     lẫn danh sách đều chỉ thấy chi nhánh của người gọi. Một bộ lọc ở tầng ứng
         *     dụng quên ở đây sẽ không rò gì — đó là lý do cô lập nằm ở DB (RT-04).
         */
        get: operations["read_audit_log_api_v1_system_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Branches
         * @description Danh mục chi nhánh của dataset đang mở.
         */
        get: operations["list_branches_api_v1_system_branches_get"];
        put?: never;
        /**
         * Create Branch
         * @description Tạo chi nhánh mới — **thực hiện đúng một lần** (FR-NFR-004).
         *
         *     Danh mục chi nhánh cố ý **không** bật RLS (xem migration `0001`): policy
         *     `WITH CHECK (id = ANY(scope))` sẽ khiến không ai tạo được chi nhánh đầu tiên,
         *     vì `id` do sequence cấp lúc `INSERT` và không thể nằm sẵn trong phạm vi của
         *     người tạo. Ai được sửa danh mục là câu hỏi của RBAC — chính dependency ở
         *     trên — không phải của cô lập dòng.
         *
         *     Lần gửi lại trả `200` kèm chính chi nhánh đã tạo, không phải `201`: mã trạng
         *     thái là chỗ duy nhất client biết được lần này có tạo thêm gì hay không.
         */
        post: operations["create_branch_api_v1_system_branches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/branches/{branch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Branch
         * @description Sửa chi nhánh, có kiểm phiên bản (FR-NFR-005).
         *
         *     `PUT` nên **không** đòi `X-Idempotency-Key`: gửi lại đúng thân request này
         *     lần thứ hai cho ra đúng trạng thái đó, và `row_version` đã chặn sẵn việc ghi
         *     đè lên thay đổi của người khác.
         */
        put: operations["update_branch_api_v1_system_branches__branch_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Available Datasets
         * @description Dữ liệu kế toán đang hoạt động trên bản cài này.
         *
         *     Không cần header `X-Dataset` — đây chính là endpoint client gọi để **biết**
         *     có thể đặt gì vào header đó.
         *
         *     Trả về mọi dataset đang hoạt động chứ không lọc theo vai trò: lọc đòi mở
         *     từng schema để đọc `user_roles`, tức là N transaction cho một màn hình chọn.
         *     Không rò gì đáng kể — mã và tên doanh nghiệp trên bản cài mà người này đã
         *     đăng nhập được — còn cửa thật thì vẫn khóa: chọn một dataset không có vai trò
         *     sẽ nhận `dataset.access_denied` ở request kế tiếp.
         */
        get: operations["list_available_datasets_api_v1_system_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/handshake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Handshake
         * @description Phiên bản của máy chủ và bản client tối thiểu nó nhận (LD-05, FR-NFR-054).
         *
         *     **Endpoint ẩn danh duy nhất của nhóm này**, và cố ý như vậy: client gọi nó
         *     ở màn hình đầu tiên, trước cả khi có ai gõ mật khẩu. Một bản client quá cũ
         *     phải biết mình cần cập nhật ngay lúc đó — biết sau khi đăng nhập rồi nhập
         *     xong một chứng từ là biết quá muộn.
         *
         *     Không chạm cơ sở dữ liệu: mọi con số ở đây thuộc về **tiến trình** đang
         *     chạy. `control_schema_version` là phiên bản mà mã nguồn này đòi hỏi, và
         *     `lifespan` đã từ chối khởi động nếu DB lệch khỏi nó — nên đọc lại từ DB chỉ
         *     thêm một truy vấn cho một endpoint mà mọi máy trạm gọi lúc khởi động.
         */
        get: operations["handshake_api_v1_system_handshake_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Settings
         * @description Toàn bộ danh mục kèm giá trị **đang có hiệu lực** cho người gọi.
         *
         *     Trả cả khóa chưa ai cấu hình (nguồn `default`): màn hình thiết lập phải dựng
         *     được từ đúng một lượt gọi, và một danh sách chỉ có giá trị đã lưu sẽ buộc
         *     client mang theo bản sao của catalog — bản sao sẽ lệch ngay ở phase sau.
         */
        get: operations["list_settings_api_v1_system_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Setting
         * @description Ghi một tùy chọn ở một cấp, có kiểm phiên bản (FR-NFR-005).
         *
         *     Quyền kiểm **trong thân hàm** chứ không bằng dependency, vì nó phụ thuộc
         *     `scope` nằm trong thân request: `require_permission` chạy trước khi thân
         *     request được phân giải. Dependency ở chữ ký vẫn giữ mức sàn (`view`), nên
         *     người không có quyền gì dừng lại từ trước đó.
         */
        put: operations["update_setting_api_v1_system_settings__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/users/{user_id}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Branch
         * @description Cho một người dùng thấy thêm một chi nhánh (FR-SYS-072).
         *
         *     Chỉ gán được chi nhánh mà **chính người thực hiện** đang thấy: nếu không,
         *     ai có `system.user.edit` cũng tự nới phạm vi của mình sang mọi chi nhánh
         *     còn lại trong một request, và cô lập chi nhánh không ngăn được gì.
         */
        post: operations["assign_branch_api_v1_system_users__user_id__branches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/users/{user_id}/branches/{branch_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Branch
         * @description Thu lại quyền xem một chi nhánh. Cùng luật phạm vi với đường gán.
         */
        delete: operations["revoke_branch_api_v1_system_users__user_id__branches__branch_code__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/users/{user_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant Role
         * @description Gán vai trò cho một người dùng trong dataset đang mở (FR-SYS-071).
         *
         *     Vai trò mang quyền nhạy cảm sẽ bật `users.totp_required` **trước** khi ghi
         *     vai trò — xem thứ tự fail-safe ở `kernel/security/role_service.py`.
         */
        post: operations["grant_role_api_v1_system_users__user_id__roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/users/{user_id}/roles/{role_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Role
         * @description Gỡ vai trò. Không tắt `totp_required` — xem `role_service.revoke_role`.
         */
        delete: operations["revoke_role_api_v1_system_users__user_id__roles__role_code__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Smoke check — không chạm cơ sở dữ liệu.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/updates/download/{target}/{arch}/{file_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Package
         * @description Phục vụ gói — **chỉ** những tệp có tên trong danh mục.
         *
         *     Danh sách trắng chứ không lọc chuỗi: đường dẫn duy nhất chạm đĩa được dựng
         *     từ tên đã nằm sẵn trong `index.json`, nên không có phép ghép nào để `..` hay
         *     một đường tuyệt đối lọt vào. Lọc chuỗi thì phải nghĩ ra đủ mọi cách viết
         *     `..`; danh sách trắng thì không cần nghĩ ra cách nào.
         */
        get: operations["download_package_updates_download__target___arch___file_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/updates/{target}/{arch}/{current_version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check For Update
         * @description Trả manifest khi có bản mới hơn; `204 No Content` khi không.
         *
         *     Mọi lối "không có gì để giao" đều đi về `204`, kể cả khi đường tự cập nhật
         *     chưa được bật hay `current_version` không đọc được. Updater hiểu đúng một
         *     tín hiệu đó, và một máy trạm không cập nhật được vẫn phải làm việc bình
         *     thường — hôm nay nó vẫn ghi sổ được, chỉ là chưa lên bản mới.
         */
        get: operations["check_for_update_updates__target___arch___current_version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessResponse
         * @description Quyền hiệu lực của người đang gọi, **trong dataset của request**.
         *
         *     Client dùng để ẩn menu và nút — không phải để quyết định cho phép: mọi lần
         *     kiểm thật vẫn nằm ở server (`require_permission`). Trả về đây chỉ để màn
         *     hình không mời người dùng bấm vào thứ chắc chắn bị từ chối.
         */
        AccessResponse: {
            /** Acting Branch Id */
            acting_branch_id: number | null;
            /** Branch Ids */
            branch_ids: number[];
            /** Dataset Code */
            dataset_code: string;
            /** Permissions */
            permissions: string[];
        };
        /**
         * AuditEntryResponse
         * @description Một dòng nhật ký nghiệp vụ (FR-NFR-013).
         */
        AuditEntryResponse: {
            /** Action */
            action: string;
            /** Branch Id */
            branch_id: number | null;
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Id */
            id: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** User Id */
            user_id: number;
        };
        /** AuditListResponse */
        AuditListResponse: {
            /** Items */
            items: components["schemas"]["AuditEntryResponse"][];
            /** Total */
            total: number;
        };
        /** BranchCreateRequest */
        BranchCreateRequest: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Name En */
            name_en?: string | null;
        };
        /** BranchGrantRequest */
        BranchGrantRequest: {
            /** Branch Code */
            branch_code: string;
        };
        /** BranchListResponse */
        BranchListResponse: {
            /** Items */
            items: components["schemas"]["BranchResponse"][];
        };
        /** BranchResponse */
        BranchResponse: {
            /** Code */
            code: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Name En */
            name_en: string | null;
            /** Row Version */
            row_version: number;
        };
        /**
         * BranchUpdateRequest
         * @description Sửa chi nhánh. `code` không sửa được — nó là mã đối chiếu của cả sổ sách.
         *
         *     `row_version` **bắt buộc**, không có mặc định: một trường tùy chọn ở đây
         *     nghĩa là client nào quên gửi sẽ ghi đè im lặng, tức là đúng cái mà khóa lạc
         *     quan sinh ra để chặn.
         */
        BranchUpdateRequest: {
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Name En */
            name_en?: string | null;
            /** Row Version */
            row_version: number;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /**
             * Current Password
             * Format: password
             */
            current_password: string;
            /**
             * New Password
             * Format: password
             */
            new_password: string;
        };
        /** DatasetListResponse */
        DatasetListResponse: {
            /** Items */
            items: components["schemas"]["DatasetSummary"][];
        };
        /**
         * DatasetSummary
         * @description Một dữ liệu kế toán trong màn hình chọn (FR-SYS-001).
         */
        DatasetSummary: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Scheme */
            scheme: string;
        };
        /**
         * GrantResponse
         * @description `changed=False` nghĩa là đã có sẵn — gọi lại không phải lỗi.
         *
         *     Idempotent có chủ đích: màn hình phân quyền là nơi người ta bấm hai lần vì
         *     không chắc lần đầu đã ăn chưa, và một lỗi `409` ở đó chỉ làm họ hoang mang.
         */
        GrantResponse: {
            /** Changed */
            changed: boolean;
        };
        /**
         * HandshakeResponse
         * @description Bắt tay client ↔ server, gọi **trước khi đăng nhập** (LD-05, FR-NFR-054).
         *
         *     Không đòi xác thực, vì đúng cái nó trả lời là câu hỏi *có đăng nhập được
         *     không*: một client quá cũ phải biết điều đó ở màn hình đầu tiên, chứ không
         *     phải sau khi người dùng gõ xong mật khẩu và bấm lưu một chứng từ.
         *
         *     Nội dung giữ ở mức tối thiểu cần cho quyết định của client. Đây là endpoint
         *     **ẩn danh** trong LAN, nên mỗi trường thêm vào là một thứ ai cũng đọc được:
         *     không có tên doanh nghiệp, không có danh sách dữ liệu kế toán, không có tên
         *     máy chủ.
         */
        HandshakeResponse: {
            /** Control Schema Version */
            control_schema_version: string;
            /** Deployment Mode */
            deployment_mode: string;
            /** Min Client Version */
            min_client_version: string;
            /** Server Version */
            server_version: string;
        };
        /**
         * HealthResponse
         * @description Trả lời của `/health`. Pydantic ở mọi ranh giới API (ADR-015).
         */
        HealthResponse: {
            /** Deployment Mode */
            deployment_mode: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * JobEnqueueRequest
         * @description Yêu cầu xếp một tác vụ vào hàng đợi.
         */
        JobEnqueueRequest: {
            /** Params */
            params?: {
                [key: string]: string | number | boolean | null;
            } | null;
            /** Type */
            type: string;
        };
        /** JobListResponse */
        JobListResponse: {
            /** Items */
            items: components["schemas"]["JobResponse"][];
        };
        /**
         * JobResponse
         * @description Trạng thái một tác vụ, đủ để màn hình vẽ thanh tiến độ.
         */
        JobResponse: {
            /** Attempt */
            attempt: number;
            /** Branch Id */
            branch_id: number | null;
            /** Cancel Requested */
            cancel_requested: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Message */
            message: string | null;
            /** Progress */
            progress: number;
            /** Requested By */
            requested_by: number;
            /** Result */
            result: {
                [key: string]: string | number | boolean | null;
            } | null;
            /** Resume Semantics */
            resume_semantics: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Type */
            type: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "done" | "failed" | "cancelled";
        /** JobTypeListResponse */
        JobTypeListResponse: {
            /** Items */
            items: components["schemas"]["JobTypeResponse"][];
        };
        /**
         * JobTypeResponse
         * @description Một loại tác vụ mà bản cài này biết chạy.
         *
         *     Lộ ra để màn hình dựng được danh sách "chạy tác vụ" từ đúng một lượt gọi,
         *     thay vì mang một bản sao của registry trong client — bản sao sẽ lệch ngay ở
         *     phase sau, khi mỗi phân hệ thêm loại của mình.
         */
        JobTypeResponse: {
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Permission */
            permission: string;
            /** Requires Privileged Connection */
            requires_privileged_connection: boolean;
            /** Resume Semantics */
            resume_semantics: string;
        };
        /**
         * LoginRequest
         * @description Đăng nhập. `totp_code` chỉ cần cho tài khoản bắt buộc 2FA.
         *
         *     Client bình thường gửi lần đầu **không** kèm mã; nhận `auth.totp_required`
         *     thì hỏi mã rồi gửi lại. Nhờ vậy màn hình đăng nhập không phải hỏi mã 2FA của
         *     những người không dùng 2FA.
         */
        LoginRequest: {
            /**
             * Password
             * Format: password
             */
            password: string;
            /** Totp Code */
            totp_code?: string | null;
            /** Username */
            username: string;
        };
        /**
         * LoginResponse
         * @description Phiên vừa cấp. `token` chỉ xuất hiện ở đây, không bao giờ đọc lại được.
         */
        LoginResponse: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Must Change Password */
            must_change_password: boolean;
            session_scope: components["schemas"]["SessionScope"];
            /** Token */
            token: string;
        };
        /**
         * MeResponse
         * @description Danh tính của phiên hiện tại. Chưa có vai trò/quyền — chúng per-dataset.
         *
         *     Quyền trả riêng theo dataset ở `GET /api/v1/system/access`, vì cùng một
         *     người có vai trò khác nhau ở mỗi dữ liệu kế toán.
         */
        MeResponse: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Locale */
            locale: string;
            /** Must Change Password */
            must_change_password: boolean;
            session_scope: components["schemas"]["SessionScope"];
            /** User Id */
            user_id: number;
            /** Username */
            username: string;
        };
        /**
         * ProblemDetails
         * @description Thân lỗi RFC 7807 — **hợp đồng công khai** với client.
         *
         *     Khai thành model (dù handler vẫn dựng `dict` để mang thêm trường tùy lớp
         *     lỗi) vì đúng một lý do: nó phải có mặt trong đặc tả OpenAPI, và từ đó có mặt
         *     trong type sinh cho client (bước 14). Không khai thì client bắt lỗi bằng
         *     `any` — tức là phần *hay xảy ra nhất* của một API lại là phần duy nhất không
         *     có kiểu.
         *
         *     `model_config` cho phép trường thừa: mỗi lớp lỗi được khai thêm trường riêng
         *     qua `problem_extra()` (`latest` của xung đột phiên bản, `errors` của lỗi
         *     kiểm dữ liệu). Chúng là phần **mở rộng** của hợp đồng, không phải phần vi
         *     phạm nó.
         */
        ProblemDetails: {
            /** Correlation Id */
            correlation_id?: string | null;
            /** Detail */
            detail: string;
            /** Details */
            details?: {
                [key: string]: string | number | null;
            } | null;
            /** Error Code */
            error_code: string;
            /** Errors */
            errors?: {
                [key: string]: unknown;
            }[] | null;
            /** Latest */
            latest?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
        } & {
            [key: string]: unknown;
        };
        /** RoleGrantRequest */
        RoleGrantRequest: {
            /** Role Code */
            role_code: string;
        };
        /**
         * SessionScope
         * @description Phiên này dùng được cho việc gì.
         *
         *     `TOTP_ENROLLMENT` gỡ một điểm chặn có thật: tài khoản bị bắt bật 2FA mà chưa
         *     đăng ký thiết bị thì không đăng nhập được, mà không đăng nhập được thì cũng
         *     không gọi được endpoint đăng ký. Trước lát này, đường thoát duy nhất là một
         *     lệnh chạy tại máy chủ — nghĩa là mỗi lần gán vai trò nhạy cảm là một cuộc gọi
         *     hỗ trợ.
         *
         *     Phiên hạn chế **không** phải phiên đầy đủ có cờ: nó là một giá trị trong cột,
         *     và mọi dependency đọc cột đó. Khác biệt quan trọng vì mặc định phải là "chặn"
         *     — thêm endpoint mới mà quên nghĩ tới 2FA thì endpoint đó bị chặn, chứ không
         *     phải mở.
         * @enum {string}
         */
        SessionScope: "full" | "totp_enrollment";
        /** SettingListResponse */
        SettingListResponse: {
            /** Items */
            items: components["schemas"]["SettingResponse"][];
        };
        /**
         * SettingResponse
         * @description Một tùy chọn với giá trị đang có hiệu lực cho người gọi.
         */
        SettingResponse: {
            /** Description */
            description: string;
            /** Key */
            key: string;
            /** Scopes */
            scopes: string[];
            /** Source */
            source: string;
            /** System Row Version */
            system_row_version: number | null;
            /** User Row Version */
            user_row_version: number | null;
            /** Value */
            value: string;
            /** Value Type */
            value_type: string;
        };
        /**
         * SettingScope
         * @description Cấp của một tùy chọn (BR-SYS-06).
         * @enum {string}
         */
        SettingScope: "system" | "user";
        /**
         * SettingUpdateRequest
         * @description Ghi một tùy chọn ở đúng một cấp.
         *
         *     `row_version` là phiên bản của dòng **ở chính cấp `scope`** — không phải
         *     của giá trị đang hiệu lực. Khai tường minh cả khi bằng `null`: "tôi tin
         *     rằng chưa ai ghi khóa này ở cấp này" cũng là một khẳng định về hiện trạng,
         *     và nó sai được y như một số phiên bản cũ.
         */
        SettingUpdateRequest: {
            /** Row Version */
            row_version?: number | null;
            scope: components["schemas"]["SettingScope"];
            /** Value */
            value: string;
        };
        /** TotpConfirmRequest */
        TotpConfirmRequest: {
            /** Code */
            code: string;
        };
        /**
         * TotpEnrollRequest
         * @description Bắt đầu đăng ký 2FA — phải nhập lại mật khẩu.
         *
         *     Đã có phiên hợp lệ vẫn phải chứng minh lại: gắn thiết bị sinh mã là thao tác
         *     quyết định ai giữ được tài khoản về sau, và một máy trạm bỏ quên không khóa
         *     màn hình không được phép làm việc đó.
         */
        TotpEnrollRequest: {
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /**
         * TotpEnrollResponse
         * @description URI `otpauth://` để client dựng mã QR.
         *
         *     **Chứa bí mật dạng rõ.** Chỉ trả đúng một lần cho chính người đang đăng ký;
         *     không ghi log, không ghi nhật ký, không lưu lại ở client.
         */
        TotpEnrollResponse: {
            /** Provisioning Uri */
            provisioning_uri: string;
        };
        /**
         * UpdateManifest
         * @description Khuôn manifest của updater Tauri v2 — **tên trường do Tauri định**.
         *
         *     Đổi tên bất kỳ trường nào ở đây là updater bỏ qua bản cập nhật trong im
         *     lặng: nó không báo lỗi khuôn, nó chỉ coi như không có gì mới.
         */
        UpdateManifest: {
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Pub Date */
            pub_date: string;
            /** Signature */
            signature: string;
            /** Url */
            url: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    confirm_totp_api_v1_auth_totp_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    enroll_totp_api_v1_auth_totp_enroll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpEnrollRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpEnrollResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    enqueue_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobEnqueueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list_job_types_api_v1_jobs_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobTypeListResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    my_access_api_v1_system_access_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    read_audit_log_api_v1_system_audit_log_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditListResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list_branches_api_v1_system_branches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchListResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    create_branch_api_v1_system_branches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    update_branch_api_v1_system_branches__branch_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list_available_datasets_api_v1_system_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetListResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    handshake_api_v1_system_handshake_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandshakeResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list_settings_api_v1_system_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingListResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    update_setting_api_v1_system_settings__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    assign_branch_api_v1_system_users__user_id__branches_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchGrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    revoke_branch_api_v1_system_users__user_id__branches__branch_code__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
                branch_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    grant_role_api_v1_system_users__user_id__roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleGrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    revoke_role_api_v1_system_users__user_id__roles__role_code__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
                role_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    download_package_updates_download__target___arch___file_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target: string;
                arch: string;
                file_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    check_for_update_updates__target___arch___current_version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target: string;
                arch: string;
                current_version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateManifest"];
                };
            };
            /** @description Không có bản nào mới hơn */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lỗi (RFC 7807) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
