"""Nền tảng: phân quyền, nhật ký bất biến, idempotency, hàng đợi job, đánh số.

Revision ID: 0001
Revises:
Create Date: 2026-08-15

Migration này chạy **một lần cho mỗi schema dataset** (ADR-017), không phải một
lần cho cả database — xem `migrations/env.py`. Phải chạy bằng vai trò
`ket_owner`: bảng do vai trò nào tạo thì vai trò đó sở hữu, và toàn bộ cơ chế
"nhật ký bất biến" (RT-02) dựa trên việc vai trò runtime **không** sở hữu bảng.

Không có khóa ngoại nào trỏ ra ngoài schema này (kể cả tới `public.users`) — một
schema dataset phải dump/restore độc lập được (RT-03/RT-14).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.dialects import postgresql

from ket.kernel.auditing.models import AUDIT_TABLE_NAME
from ket.kernel.datasets.naming import role_name_for_schema
from ket.kernel.datasets.provisioning import ALEMBIC_SCHEMA_ATTRIBUTE
from ket.kernel.security.grants import (
    grant_append_only,
    grant_read_write,
    serial_sequence_name,
)
from ket.kernel.security.rls import enable_branch_rls_statements

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=True),
        sa.Column("entity_type", sa.String(length=150), nullable=False),
        sa.Column("entity_id", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("old_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("correlation_id", sa.UUID(), nullable=True),
        sa.Column("client_info", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "action IN ('created', 'updated', 'deleted', 'posted', 'unposted', 'locked', 'unlocked', 'printed')",
            name=op.f("ck_audit_log_action_known"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_entity",
        "audit_log",
        ["entity_type", "entity_id", "occurred_at"],
        unique=False,
    )
    op.create_index("ix_audit_log_occurred_at", "audit_log", ["occurred_at"], unique=False)
    op.create_index("ix_audit_log_user", "audit_log", ["user_id", "occurred_at"], unique=False)
    op.create_table(
        "branches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("name_en", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_branches")),
        sa.UniqueConstraint("code", name=op.f("uq_branches_code")),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("route_key", sa.String(length=150), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("result_type", sa.String(length=100), nullable=False),
        sa.Column("result_id", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("route_key", "idempotency_key", name=op.f("pk_idempotency_keys")),
    )
    op.create_index(
        "ix_idempotency_keys_expires_at", "idempotency_keys", ["expires_at"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="queued", nullable=False),
        sa.Column("progress", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("branch_id", sa.Integer(), nullable=True),
        sa.Column("requested_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "cancel_requested", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("resume_semantics", sa.String(length=30), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'done', 'failed', 'cancelled')",
            name=op.f("ck_jobs_status_known"),
        ),
        sa.CheckConstraint("progress BETWEEN 0 AND 100", name=op.f("ck_jobs_progress_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(
        "ix_jobs_lease",
        "jobs",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_index(
        "ix_jobs_queue",
        "jobs",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_table(
        "number_sequences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_key", sa.String(length=150), nullable=False),
        sa.Column("prefix", sa.String(length=50), server_default="", nullable=False),
        sa.Column("padding", sa.Integer(), server_default="5", nullable=False),
        sa.Column("next_value", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("allow_gaps", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_number_sequences")),
        sa.UniqueConstraint("scope_key", name=op.f("uq_number_sequences_scope_key")),
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("code", name=op.f("uq_permissions_code")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("name_en", sa.String(length=255), nullable=True),
        sa.Column("is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_roles_code")),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope", sa.String(length=10), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.String(length=1000), nullable=False),
        sa.Column("value_type", sa.String(length=20), server_default="string", nullable=False),
        sa.CheckConstraint(
            "(scope = 'system' AND user_id IS NULL) OR (scope = 'user' AND user_id IS NOT NULL)",
            name=op.f("ck_settings_scope_user_consistent"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
    )
    op.create_index(
        "uq_settings_system_key",
        "settings",
        ["key"],
        unique=True,
        postgresql_where=sa.text("scope = 'system'"),
    )
    op.create_index(
        "uq_settings_user_key",
        "settings",
        ["user_id", "key"],
        unique=True,
        postgresql_where=sa.text("scope = 'user'"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("allow", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_role_permissions_role_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "user_branches",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_user_branches_branch_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "branch_id", name=op.f("pk_user_branches")),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    # ### end Alembic commands ###

    _apply_grants()
    _apply_row_level_security()


def _apply_grants() -> None:
    """Phân quyền bảng cho vai trò runtime (RT-02).

    `audit_log` là bảng **chỉ thêm**: `ket_app` không `UPDATE`/`DELETE`/
    `TRUNCATE`/`DROP` được, kể cả khi app server bị chiếm quyền hoàn toàn. Cơ
    chế này chỉ có hiệu lực khi bảng thuộc `ket_owner` — chủ sở hữu bảng tự
    bỏ qua `REVOKE` của chính mình, nên nếu migration chạy bằng vai trò runtime
    thì "bất biến" chỉ còn là lời hứa.
    """
    append_only = {AUDIT_TABLE_NAME}
    tables_with_serial_id = {
        "branches",
        "roles",
        "permissions",
        "settings",
        "number_sequences",
        AUDIT_TABLE_NAME,
    }
    all_tables = (
        AUDIT_TABLE_NAME,
        "branches",
        "roles",
        "permissions",
        "role_permissions",
        "user_roles",
        "user_branches",
        "settings",
        "idempotency_keys",
        "jobs",
        "number_sequences",
    )

    grantee = _dataset_grantee()
    for table in all_tables:
        sequence = serial_sequence_name(table) if table in tables_with_serial_id else None
        builder = grant_append_only if table in append_only else grant_read_write
        for statement in builder(table, grantee=grantee, sequence=sequence):
            op.execute(statement)


def _dataset_grantee() -> str:
    """Vai trò nhận quyền trên bảng của **schema đang được migrate** (D3).

    Lấy schema từ `Config.attributes` — chỗ mà `migrations/env.py` ghi lại kết
    quả phân giải của chính nó — chứ không hỏi DB `current_schema()`. Hai lý do:

    * Chế độ offline (`alembic upgrade --sql`) **không có connection thật**;
      `op.get_bind()` trả `MockConnection` và một lời gọi `exec_driver_sql` ở đây
      làm vỡ hẳn chế độ sinh SQL — thứ mà DBA của khách hàng dùng để duyệt
      migration trước khi chạy.
    * Vẫn chỉ có một nơi phân giải schema (`env.py::_resolve_schema`), nên không
      mở đường thứ hai để migration của dataset này cấp quyền lên bảng của
      dataset kia.
    """
    schema = context.config.attributes.get(ALEMBIC_SCHEMA_ATTRIBUTE)
    if not isinstance(schema, str):
        raise RuntimeError(
            f"Không xác định được schema đích: `{ALEMBIC_SCHEMA_ATTRIBUTE}` chưa được "
            "`migrations/env.py` ghi vào Config.attributes"
        )
    return role_name_for_schema(schema)


def _apply_row_level_security() -> None:
    """Cô lập chi nhánh ở tầng DB (RT-04, FR-SYS-072).

    Bật cho mọi bảng mang **dữ liệu** gắn chi nhánh. Ở phase này là `audit_log`
    và `jobs`; từ phase 4 mọi bảng phát sinh đều vào danh sách này.

    Hai bảng cố ý **không** bật, mỗi bảng một lý do khác nhau:

    * `user_branches` — nó là **nguồn** dựng nên phạm vi RLS. Bật lên thành
      vòng lặp: muốn biết được xem chi nhánh nào thì đã phải biết được xem chi
      nhánh nào.
    * `branches` — danh mục chi nhánh, không phải dữ liệu phát sinh. Policy
      `WITH CHECK (id = ANY(scope))` sẽ khiến **không ai tạo được chi nhánh
      mới**: id do sequence cấp ngay lúc `INSERT` và không thể nằm sẵn trong
      phạm vi của người tạo. Ai được xem/sửa danh mục chi nhánh là câu hỏi của
      RBAC (`permissions`), không phải của cô lập dòng.

    `allow_null_branch=True` cho cả hai: `branch_id IS NULL` nghĩa là sự kiện /
    tác vụ mức hệ thống (đăng nhập, tạo dataset, đổi cấu hình chung). Không cho
    NULL đi qua thì chúng vô hình với **mọi** người dùng, kể cả quản trị viên.
    """
    for table in (AUDIT_TABLE_NAME, "jobs"):
        for statement in enable_branch_rls_statements(table, allow_null_branch=True):
            op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("user_branches")
    op.drop_table("role_permissions")
    op.drop_index(
        "uq_settings_user_key", table_name="settings", postgresql_where=sa.text("scope = 'user'")
    )
    op.drop_index(
        "uq_settings_system_key",
        table_name="settings",
        postgresql_where=sa.text("scope = 'system'"),
    )
    op.drop_table("settings")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_table("number_sequences")
    op.drop_index("ix_jobs_queue", table_name="jobs", postgresql_where=sa.text("status = 'queued'"))
    op.drop_index(
        "ix_jobs_lease", table_name="jobs", postgresql_where=sa.text("status = 'running'")
    )
    op.drop_table("jobs")
    op.drop_index("ix_idempotency_keys_expires_at", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_table("branches")
    op.drop_index("ix_audit_log_user", table_name="audit_log")
    op.drop_index("ix_audit_log_occurred_at", table_name="audit_log")
    op.drop_index("ix_audit_log_entity", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
